### PR TITLE
Update WellKnownPrincipal.cs

### PR DESCRIPTION
**Pull request by Argentix03**
## Description

The correct type for the IUSR (S-1-5-17) is user, not group.
  this small thing made a huge confusion for some people today :( i think this was caused from copy pasting s-1-5-15 the one above it in a fix long ago.

do not confuse IUSR type with IIS_IUSRS
https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/manage/understand-security-identifiers
## Motivation and Context

this small thing made a huge confusion for some people today :( 
i think this was caused from copy pasting s-1-5-15 the one above it in a fix long ago.

## How Has This Been Tested?
single run on empty dc with iis installed

## Types of changes

-   [ ] Chore (a change that does not modify the application functionality)
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-   [ ] Documentation updates are needed, and have been made accordingly.
-   [ ] I have added and/or updated tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] My changes include a database migration.

### CODE REVIEW

**Comment by Argentix03** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rvazarkar** [comment]
Could you retarget this against the `utils_rewrite` branch as this will be used starting this coming week?

**Comment by rvazarkar** [comment]
You'll also need to fix the test in `WellKnownPrincipalTest.cs`

**Comment by Argentix03** [comment]
- [x] retarget branch 
- [x] fix test

**Review by rvazarkar — APPROVED** [review]

**Comment by rvazarkar** [comment]
Thanks for the MR, looks great!

**Pull request merged**
