### PR TITLE
Implement DumpSMSAPassword edge

### PR DESCRIPTION
**Pull request by JonasBK**

### CODE REVIEW

**Comment by JonasBK** [comment]
recheck

**Comment by JonasBK** [comment]
recheck

**Comment by JonasBK** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by JonasBK** [comment]
recheck

**Comment by rvazarkar** [comment]
Got my approval, going to see if anyone else wants to review before merging

**Review by rvazarkar — APPROVED** [review]

**Pull request merged**
